#!/bin/sh

pretty_print() {
  TEXT=$1
  BLUE='\033[0;34m'
  NC='\033[0m'

  echo "$BLUE>> $TEXT$NC"
}

pretty_print "Generation"
rustfmt generation/**.rs
./gen

pretty_print "Tests"
cargo test --quiet

pretty_print "Doc"
./doc
cp -a target/doc/. docs/
echo '<meta http-equiv=refresh content=0;url=lay/index.html>' > docs/index.html
echo "file:$PWD/docs/lay/index.html"

pretty_print "Generation doc"
(cd generation && cargo doc --quiet --no-deps)
echo "file:$PWD/generation/target/doc/generation/index.html"
