#!/bin/sh

if [ "$1" = "watch" ]; then
  cargo watch -s "clear; ./doc"
else
  cargo doc --quiet --document-private-items --target-dir target/doc_priv
  echo "file:$PWD/target/doc_priv/doc/lay/index.html"
fi
