#!/bin/sh

if [ "$1" = "watch" ]; then
  cargo watch      \
    -w generation/ \
    -s "clear; ./gen; cargo doc --quiet --no-deps"
else
  (cd generation && cargo run --quiet "$1")
  cargo check --quiet
  rustfmt src/**.rs
  rustfmt examples/**.rs
fi
