#!/bin/sh

if [ "$1" = "watch" ]; then
  cargo watch      \
    -w generation/ \
    -s "clear; ./gen; ./doc"
else
  (cd generation && cargo run --quiet)
  rustfmt src/**.rs
  rustfmt examples/**.rs
  cargo check --quiet
fi
