#!/bin/sh

if [ "$1" = "watch" ]; then
  cargo watch      \
    -w generation/ \
    -s "clear; ./gen"
else
  (cd generation && cargo run --quiet)
  rustfmt +nightly src/**.rs
  rustfmt +nightly examples/**.rs
  cargo check --quiet
  ./doc
fi
