////////////////////////////////////////////////////////////////////////////////
// 🚨🚨🚨🚨🚨🚨🚨🚨 This file is @generated by build script. 🚨🚨🚨🚨🚨🚨🚨🚨 //
// 🚧🚧🚧🚧🚧🚧🚧🚧           ⛔ DO NOT MODIFY! ⛔           🚧🚧🚧🚧🚧🚧🚧🚧 //
////////////////////////////////////////////////////////////////////////////////

use crate::*;

/// A trait for getting `Option`al attributes on styled types.
pub trait StylerIndex {
    /// Gets `Option<Foreground>`.
    fn get_foreground(&self) -> Option<Foreground>;

    /// Gets `Option<Background>`.
    fn get_background(&self) -> Option<Background>;

    /// Gets `Option<Weight>`.
    fn get_weight(&self) -> Option<Weight>;

    /// Gets `Option<Slant>`.
    fn get_slant(&self) -> Option<Slant>;

    /// Gets `Option<Underline>`.
    fn get_underline(&self) -> Option<Underline>;

    /// Gets `Option<Strike>`.
    fn get_strike(&self) -> Option<Strike>;

    /// Gets `Option<Overline>`.
    fn get_overline(&self) -> Option<Overline>;

    /// Gets `Option<Invert>`.
    fn get_invert(&self) -> Option<Invert>;

    /// Gets `Option<Blink>`.
    fn get_blink(&self) -> Option<Blink>;

    /// Gets `Option<Border>`.
    fn get_border(&self) -> Option<Border>;

    /// Returns a `Style`.
    fn to_style(&self) -> Style {
        Style {
            foreground: self.get_foreground(),
            background: self.get_background(),
            weight:     self.get_weight(),
            slant:      self.get_slant(),
            underline:  self.get_underline(),
            strike:     self.get_strike(),
            overline:   self.get_overline(),
            invert:     self.get_invert(),
            blink:      self.get_blink(),
            border:     self.get_border(),
        }
    }
}
