////////////////////////////////////////////////////////////////////////////////
// 🚨🚨🚨🚨🚨🚨🚨🚨 This file is @generated by build script. 🚨🚨🚨🚨🚨🚨🚨🚨 //
// 🚧🚧🚧🚧🚧🚧🚧🚧           ⛔ DO NOT MODIFY! ⛔           🚧🚧🚧🚧🚧🚧🚧🚧 //
////////////////////////////////////////////////////////////////////////////////

//! Attributes (`Foreground`, `Background`, `Weight`, `Slant`, `Underline`,
//! `Strike`, `Overline`, `Invert`, `Blink`, `Border`).

mod background;
mod blink;
mod border;
mod foreground;
mod invert;
mod overline;
mod slant;
mod strike;
mod underline;
mod weight;

pub use background::*;
pub use blink::*;
pub use border::*;
pub use foreground::*;
pub use invert::*;
pub use overline::*;
pub use slant::*;
pub use strike::*;
pub use underline::*;
pub use weight::*;
