////////////////////////////////////////////////////////////////////////////////
// 🚨🚨🚨🚨🚨🚨🚨🚨 This file is @generated by build script. 🚨🚨🚨🚨🚨🚨🚨🚨 //
// 🚧🚧🚧🚧🚧🚧🚧🚧           ⛔ DO NOT MODIFY! ⛔           🚧🚧🚧🚧🚧🚧🚧🚧 //
////////////////////////////////////////////////////////////////////////////////

pub use Slant::*;

/// `Slant` (`Italic`, `ResetSlant`).
///
/// Prints the corresponding CSI to the terminal when `Display`ed.
/// `Default`s to `Slant::ResetSlant`, the unsetting CSI.
#[derive(Copy, Clone, Eq, PartialEq, Hash, Debug)]
pub enum Slant {
    Italic,
    ResetSlant,
}

/// Returns `Slant::ResetSlant`.
impl Default for Slant {
    /// Returns `Slant::ResetSlant`.
    fn default() -> Self {
        Slant::ResetSlant
    }
}
