////////////////////////////////////////////////////////////////////////////////
// 🚨🚨🚨🚨🚨🚨🚨🚨 This file is @generated by build script. 🚨🚨🚨🚨🚨🚨🚨🚨 //
// 🚧🚧🚧🚧🚧🚧🚧🚧           ⛔ DO NOT MODIFY! ⛔           🚧🚧🚧🚧🚧🚧🚧🚧 //
////////////////////////////////////////////////////////////////////////////////

pub use Strike::*;

/// `Strike` (`Striked`, `ResetStrike`).
///
/// Prints the corresponding CSI to the terminal when `Display`ed.  
/// `Default`s to `Strike::ResetStrike`, the unsetting CSI.
#[derive(Copy, Clone, Eq, PartialEq, Hash, Debug)]
pub enum Strike {
    Striked,
    ResetStrike,
}

/// Returns `Strike::ResetStrike`.
impl Default for Strike {
    /// Returns `Strike::ResetStrike`.
    fn default() -> Self {
        Strike::ResetStrike
    }
}
