////////////////////////////////////////////////////////////////////////////////
// 🚨🚨🚨🚨🚨🚨🚨🚨 This file is @generated by build script. 🚨🚨🚨🚨🚨🚨🚨🚨 //
// 🚧🚧🚧🚧🚧🚧🚧🚧           ⛔ DO NOT MODIFY! ⛔           🚧🚧🚧🚧🚧🚧🚧🚧 //
////////////////////////////////////////////////////////////////////////////////

pub use Underline::*;

/// `Underline` (`Underlined`, `ResetUnderline`).
///
/// Prints the corresponding CSI to the terminal when `Display`ed.
/// `Default`s to `ResetUnderline`, the unsetting CSI.
#[derive(Copy, Clone, Eq, PartialEq, Hash, Debug)]
pub enum Underline {
    Underlined,
    ResetUnderline,
}

/// Returns `Underline::ResetUnderline`.
impl Default for Underline {
    /// Returns `Underline::ResetUnderline`.
    fn default() -> Self {
        Self::ResetUnderline
    }
}
