////////////////////////////////////////////////////////////////////////////////
// 🚨🚨🚨🚨🚨🚨🚨🚨 This file is @generated by build script. 🚨🚨🚨🚨🚨🚨🚨🚨 //
// 🚧🚧🚧🚧🚧🚧🚧🚧           ⛔ DO NOT MODIFY! ⛔           🚧🚧🚧🚧🚧🚧🚧🚧 //
////////////////////////////////////////////////////////////////////////////////

pub use Weight::*;

/// `Weight` (`Bold`, `Light`, `ResetWeight`).
///
/// Prints the corresponding CSI to the terminal when `Display`ed.
/// `Default`s to `Weight::ResetWeight`, the unsetting CSI.
#[derive(Copy, Clone, Eq, PartialEq, Hash, Debug)]
pub enum Weight {
    Bold,
    Light,
    ResetWeight,
}

/// Returns `Weight::ResetWeight`.
impl Default for Weight {
    /// Returns `Weight::ResetWeight`.
    fn default() -> Self {
        Weight::ResetWeight
    }
}
