////////////////////////////////////////////////////////////////////////////////
// 🚨🚨🚨🚨🚨🚨🚨🚨 This file is @generated by build script. 🚨🚨🚨🚨🚨🚨🚨🚨 //
// 🚧🚧🚧🚧🚧🚧🚧🚧           ⛔ DO NOT MODIFY! ⛔           🚧🚧🚧🚧🚧🚧🚧🚧 //
////////////////////////////////////////////////////////////////////////////////

fn main() {
    use lay::*;
    // Styler
    println!(
        "{}Sweet!",
        Style::NONE
         .weight(Bold)  // Sets an attribute
         .no_slant()    // Nones an attribute
         .underlined()  // Sets a variant
         .reset_blink() // That's a variant as well
         .white()       // Sets a foreground color
         .on_dark_red() // Sets a background color
    );

    // StylerMut
    #[allow(const_item_mutation)]
    let style = &mut Style::NONE;
    style.weight_mut(Bold); //  Sets an attribute
    style.no_slant_mut(); //    Nones an attribute
    style.underlined_mut(); //  Sets a variant
    style.reset_blink_mut(); // That's a variant as well
    style.white_mut(); //       Sets a foreground color
    style.on_dark_red_mut(); // Sets a background color

    println!("{}Sick!", style);
}
