////////////////////////////////////////////////////////////////////////////////
// 🚨🚨🚨🚨🚨🚨🚨🚨 This file is @generated by build script. 🚨🚨🚨🚨🚨🚨🚨🚨 //
// 🚧🚧🚧🚧🚧🚧🚧🚧           ⛔ DO NOT MODIFY! ⛔           🚧🚧🚧🚧🚧🚧🚧🚧 //
////////////////////////////////////////////////////////////////////////////////

// 💡
// This example is generated from the documentation. Check it out:
// https://truchi.github.io/lay/lay/style/

fn main() {
    use lay::*;
    println!(
        "{}Declaring with style",
        Style::NONE.white().on_black().bold().italic() // Same as above
    );
}
