////////////////////////////////////////////////////////////////////////////////
// 🚨🚨🚨🚨🚨🚨🚨🚨 This file is @generated by build script. 🚨🚨🚨🚨🚨🚨🚨🚨 //
// 🚧🚧🚧🚧🚧🚧🚧🚧           ⛔ DO NOT MODIFY! ⛔           🚧🚧🚧🚧🚧🚧🚧🚧 //
////////////////////////////////////////////////////////////////////////////////

fn main() {
    use lay::*;
    println!(
     "{on_black}{green}{blink}{weight}# Styling utilities.{reset_blink}

     {blue}{slant}This module contains utilities to work with terminal CSIs and styled types.{reset}",
     on_black = Background(Rgb(0, 0, 0)),
     green = Foreground(Green),
     blue = Foreground(Blue),
     blink = Fast,
     reset_blink = ResetBlink,
     weight = Bold,
     slant = Italic,
     reset = Reset,
 );
}
