////////////////////////////////////////////////////////////////////////////////
// 🚨🚨🚨🚨🚨🚨🚨🚨 This file is @generated by build script. 🚨🚨🚨🚨🚨🚨🚨🚨 //
// 🚧🚧🚧🚧🚧🚧🚧🚧           ⛔ DO NOT MODIFY! ⛔           🚧🚧🚧🚧🚧🚧🚧🚧 //
////////////////////////////////////////////////////////////////////////////////

//! Attributes `None`rs.

/// `None`s `Foreground`.
#[derive(Copy, Clone, Eq, PartialEq, Hash, Default, Debug)]
pub struct Foreground;

/// `None`s `Background`.
#[derive(Copy, Clone, Eq, PartialEq, Hash, Default, Debug)]
pub struct Background;

/// `None`s `Weight`.
#[derive(Copy, Clone, Eq, PartialEq, Hash, Default, Debug)]
pub struct Weight;

/// `None`s `Slant`.
#[derive(Copy, Clone, Eq, PartialEq, Hash, Default, Debug)]
pub struct Slant;

/// `None`s `Underline`.
#[derive(Copy, Clone, Eq, PartialEq, Hash, Default, Debug)]
pub struct Underline;

/// `None`s `Strike`.
#[derive(Copy, Clone, Eq, PartialEq, Hash, Default, Debug)]
pub struct Strike;

/// `None`s `Overline`.
#[derive(Copy, Clone, Eq, PartialEq, Hash, Default, Debug)]
pub struct Overline;

/// `None`s `Invert`.
#[derive(Copy, Clone, Eq, PartialEq, Hash, Default, Debug)]
pub struct Invert;

/// `None`s `Blink`.
#[derive(Copy, Clone, Eq, PartialEq, Hash, Default, Debug)]
pub struct Blink;

/// `None`s `Border`.
#[derive(Copy, Clone, Eq, PartialEq, Hash, Default, Debug)]
pub struct Border;
