////////////////////////////////////////////////////////////////////////////////
// 🚨🚨🚨🚨🚨🚨🚨🚨 This file is @generated by build script. 🚨🚨🚨🚨🚨🚨🚨🚨 //
// 🚧🚧🚧🚧🚧🚧🚧🚧           ⛔ DO NOT MODIFY! ⛔           🚧🚧🚧🚧🚧🚧🚧🚧 //
////////////////////////////////////////////////////////////////////////////////

use crate::*;

/// `Reset`s all attributes.
#[derive(Copy, Clone, Eq, PartialEq, Hash, Default, Debug)]
pub struct Reset;

/// Returns `Some(Foreground(Color::ResetColor))`.
impl From<Reset> for Option<Foreground> {
    /// Returns `Some(Foreground(Color::ResetColor))`.
    fn from(_: Reset) -> Self {
        Some(Foreground(Color::ResetColor))
    }
}

/// Returns `Some(Background(Color::ResetColor))`.
impl From<Reset> for Option<Background> {
    /// Returns `Some(Background(Color::ResetColor))`.
    fn from(_: Reset) -> Self {
        Some(Background(Color::ResetColor))
    }
}

/// Returns `Some(Weight::ResetWeight)`.
impl From<Reset> for Option<Weight> {
    /// Returns `Some(Weight::ResetWeight)`.
    fn from(_: Reset) -> Self {
        Some(Weight::ResetWeight)
    }
}

/// Returns `Some(Slant::ResetSlant)`.
impl From<Reset> for Option<Slant> {
    /// Returns `Some(Slant::ResetSlant)`.
    fn from(_: Reset) -> Self {
        Some(Slant::ResetSlant)
    }
}

/// Returns `Some(Underline::ResetUnderline)`.
impl From<Reset> for Option<Underline> {
    /// Returns `Some(Underline::ResetUnderline)`.
    fn from(_: Reset) -> Self {
        Some(Underline::ResetUnderline)
    }
}

/// Returns `Some(Strike::ResetStrike)`.
impl From<Reset> for Option<Strike> {
    /// Returns `Some(Strike::ResetStrike)`.
    fn from(_: Reset) -> Self {
        Some(Strike::ResetStrike)
    }
}

/// Returns `Some(Overline::ResetOverline)`.
impl From<Reset> for Option<Overline> {
    /// Returns `Some(Overline::ResetOverline)`.
    fn from(_: Reset) -> Self {
        Some(Overline::ResetOverline)
    }
}

/// Returns `Some(Invert::ResetInvert)`.
impl From<Reset> for Option<Invert> {
    /// Returns `Some(Invert::ResetInvert)`.
    fn from(_: Reset) -> Self {
        Some(Invert::ResetInvert)
    }
}

/// Returns `Some(Blink::ResetBlink)`.
impl From<Reset> for Option<Blink> {
    /// Returns `Some(Blink::ResetBlink)`.
    fn from(_: Reset) -> Self {
        Some(Blink::ResetBlink)
    }
}

/// Returns `Some(Border::ResetBorder)`.
impl From<Reset> for Option<Border> {
    /// Returns `Some(Border::ResetBorder)`.
    fn from(_: Reset) -> Self {
        Some(Border::ResetBorder)
    }
}
