////////////////////////////////////////////////////////////////////////////////
// 🚨🚨🚨🚨🚨🚨🚨🚨 This file is @generated by build script. 🚨🚨🚨🚨🚨🚨🚨🚨 //
// 🚧🚧🚧🚧🚧🚧🚧🚧           ⛔ DO NOT MODIFY! ⛔           🚧🚧🚧🚧🚧🚧🚧🚧 //
////////////////////////////////////////////////////////////////////////////////

use crate::*;

/// A trait for getting `Option`al attributes on styled types.
pub trait StylerIndex {
    /// Gets `Option<Foreground>`.
    fn get_foreground(&self) -> Option<Foreground>;

    /// Gets `Option<Background>`.
    fn get_background(&self) -> Option<Background>;

    /// Gets `Option<Weight>`.
    fn get_weight(&self) -> Option<Weight>;

    /// Gets `Option<Slant>`.
    fn get_slant(&self) -> Option<Slant>;

    /// Gets `Option<Underline>`.
    fn get_underline(&self) -> Option<Underline>;

    /// Gets `Option<Strike>`.
    fn get_strike(&self) -> Option<Strike>;

    /// Gets `Option<Overline>`.
    fn get_overline(&self) -> Option<Overline>;

    /// Gets `Option<Invert>`.
    fn get_invert(&self) -> Option<Invert>;

    /// Gets `Option<Blink>`.
    fn get_blink(&self) -> Option<Blink>;

    /// Gets `Option<Border>`.
    fn get_border(&self) -> Option<Border>;

    /// Returns a `Style`.
    fn style(&self) -> Style {
        Style {
            foreground: self.get_foreground(),
            background: self.get_background(),
            weight:     self.get_weight(),
            slant:      self.get_slant(),
            underline:  self.get_underline(),
            strike:     self.get_strike(),
            overline:   self.get_overline(),
            invert:     self.get_invert(),
            blink:      self.get_blink(),
            border:     self.get_border(),
        }
    }
}

/// A trait for getting `Option`al attributes on mutable styled types.
pub trait StylerIndexMut {
    /// Gets `&mut Option<Foreground>`.
    fn get_foreground(&mut self) -> &mut Option<Foreground>;

    /// Gets `&mut Option<Background>`.
    fn get_background(&mut self) -> &mut Option<Background>;

    /// Gets `&mut Option<Weight>`.
    fn get_weight(&mut self) -> &mut Option<Weight>;

    /// Gets `&mut Option<Slant>`.
    fn get_slant(&mut self) -> &mut Option<Slant>;

    /// Gets `&mut Option<Underline>`.
    fn get_underline(&mut self) -> &mut Option<Underline>;

    /// Gets `&mut Option<Strike>`.
    fn get_strike(&mut self) -> &mut Option<Strike>;

    /// Gets `&mut Option<Overline>`.
    fn get_overline(&mut self) -> &mut Option<Overline>;

    /// Gets `&mut Option<Invert>`.
    fn get_invert(&mut self) -> &mut Option<Invert>;

    /// Gets `&mut Option<Blink>`.
    fn get_blink(&mut self) -> &mut Option<Blink>;

    /// Gets `&mut Option<Border>`.
    fn get_border(&mut self) -> &mut Option<Border>;
}

/// A trait for setting `Option`al attributes on styled types.
pub trait Styler: StylerIndex + Sized {
    /// The resulting type of the setters.
    type Output;

    /// Sets `Option<Foreground>`.
    fn foreground(self, foreground: impl Into<Option<Foreground>>) -> Self;

    /// Sets `Some(Foreground(Color::White))`.
    fn white(self) -> Self {
        self.foreground(Foreground(Color::White))
    }

    /// Sets `Some(Foreground(Color::Black))`.
    fn black(self) -> Self {
        self.foreground(Foreground(Color::Black))
    }

    /// Sets `Some(Foreground(Color::Grey))`.
    fn grey(self) -> Self {
        self.foreground(Foreground(Color::Grey))
    }

    /// Sets `Some(Foreground(Color::DarkGrey))`.
    fn dark_grey(self) -> Self {
        self.foreground(Foreground(Color::DarkGrey))
    }

    /// Sets `Some(Foreground(Color::Red))`.
    fn red(self) -> Self {
        self.foreground(Foreground(Color::Red))
    }

    /// Sets `Some(Foreground(Color::DarkRed))`.
    fn dark_red(self) -> Self {
        self.foreground(Foreground(Color::DarkRed))
    }

    /// Sets `Some(Foreground(Color::Green))`.
    fn green(self) -> Self {
        self.foreground(Foreground(Color::Green))
    }

    /// Sets `Some(Foreground(Color::DarkGreen))`.
    fn dark_green(self) -> Self {
        self.foreground(Foreground(Color::DarkGreen))
    }

    /// Sets `Some(Foreground(Color::Yellow))`.
    fn yellow(self) -> Self {
        self.foreground(Foreground(Color::Yellow))
    }

    /// Sets `Some(Foreground(Color::DarkYellow))`.
    fn dark_yellow(self) -> Self {
        self.foreground(Foreground(Color::DarkYellow))
    }

    /// Sets `Some(Foreground(Color::Blue))`.
    fn blue(self) -> Self {
        self.foreground(Foreground(Color::Blue))
    }

    /// Sets `Some(Foreground(Color::DarkBlue))`.
    fn dark_blue(self) -> Self {
        self.foreground(Foreground(Color::DarkBlue))
    }

    /// Sets `Some(Foreground(Color::Magenta))`.
    fn magenta(self) -> Self {
        self.foreground(Foreground(Color::Magenta))
    }

    /// Sets `Some(Foreground(Color::DarkMagenta))`.
    fn dark_magenta(self) -> Self {
        self.foreground(Foreground(Color::DarkMagenta))
    }

    /// Sets `Some(Foreground(Color::Cyan))`.
    fn cyan(self) -> Self {
        self.foreground(Foreground(Color::Cyan))
    }

    /// Sets `Some(Foreground(Color::DarkCyan))`.
    fn dark_cyan(self) -> Self {
        self.foreground(Foreground(Color::DarkCyan))
    }

    /// Sets `Some(Foreground(Color::Rgb(r,g,b)))`.
    fn rgb(self, r: u8, g: u8, b: u8) -> Self {
        self.foreground(Foreground(Color::Rgb(r, g, b)))
    }

    /// Sets `Some(Foreground(Color::Ansi(ansi)))`.
    fn ansi(self, ansi: u8) -> Self {
        self.foreground(Foreground(Color::Ansi(ansi)))
    }

    /// Sets `Some(Foreground(Color::ResetColor))`.
    fn reset_color(self) -> Self {
        self.foreground(Foreground(Color::ResetColor))
    }

    /// `None`s `Option<Foreground>`.
    fn no_foreground(self) -> Self {
        self.foreground(None)
    }

    /// Sets `Option<Background>`.
    fn background(self, background: impl Into<Option<Background>>) -> Self;

    /// Sets `Some(Background(Color::White))`.
    fn on_white(self) -> Self {
        self.background(Background(Color::White))
    }

    /// Sets `Some(Background(Color::Black))`.
    fn on_black(self) -> Self {
        self.background(Background(Color::Black))
    }

    /// Sets `Some(Background(Color::Grey))`.
    fn on_grey(self) -> Self {
        self.background(Background(Color::Grey))
    }

    /// Sets `Some(Background(Color::DarkGrey))`.
    fn on_dark_grey(self) -> Self {
        self.background(Background(Color::DarkGrey))
    }

    /// Sets `Some(Background(Color::Red))`.
    fn on_red(self) -> Self {
        self.background(Background(Color::Red))
    }

    /// Sets `Some(Background(Color::DarkRed))`.
    fn on_dark_red(self) -> Self {
        self.background(Background(Color::DarkRed))
    }

    /// Sets `Some(Background(Color::Green))`.
    fn on_green(self) -> Self {
        self.background(Background(Color::Green))
    }

    /// Sets `Some(Background(Color::DarkGreen))`.
    fn on_dark_green(self) -> Self {
        self.background(Background(Color::DarkGreen))
    }

    /// Sets `Some(Background(Color::Yellow))`.
    fn on_yellow(self) -> Self {
        self.background(Background(Color::Yellow))
    }

    /// Sets `Some(Background(Color::DarkYellow))`.
    fn on_dark_yellow(self) -> Self {
        self.background(Background(Color::DarkYellow))
    }

    /// Sets `Some(Background(Color::Blue))`.
    fn on_blue(self) -> Self {
        self.background(Background(Color::Blue))
    }

    /// Sets `Some(Background(Color::DarkBlue))`.
    fn on_dark_blue(self) -> Self {
        self.background(Background(Color::DarkBlue))
    }

    /// Sets `Some(Background(Color::Magenta))`.
    fn on_magenta(self) -> Self {
        self.background(Background(Color::Magenta))
    }

    /// Sets `Some(Background(Color::DarkMagenta))`.
    fn on_dark_magenta(self) -> Self {
        self.background(Background(Color::DarkMagenta))
    }

    /// Sets `Some(Background(Color::Cyan))`.
    fn on_cyan(self) -> Self {
        self.background(Background(Color::Cyan))
    }

    /// Sets `Some(Background(Color::DarkCyan))`.
    fn on_dark_cyan(self) -> Self {
        self.background(Background(Color::DarkCyan))
    }

    /// Sets `Some(Background(Color::Rgb(r,g,b)))`.
    fn on_rgb(self, r: u8, g: u8, b: u8) -> Self {
        self.background(Background(Color::Rgb(r, g, b)))
    }

    /// Sets `Some(Background(Color::Ansi(ansi)))`.
    fn on_ansi(self, ansi: u8) -> Self {
        self.background(Background(Color::Ansi(ansi)))
    }

    /// Sets `Some(Background(Color::ResetColor))`.
    fn on_reset_color(self) -> Self {
        self.background(Background(Color::ResetColor))
    }

    /// `None`s `Option<Background>`.
    fn no_background(self) -> Self {
        self.background(None)
    }

    /// Sets `Option<Weight>`.
    fn weight(self, weight: impl Into<Option<Weight>>) -> Self;

    /// Sets `Some(Weight::Bold)`.
    fn bold(self) -> Self {
        self.weight(Weight::Bold)
    }

    /// Sets `Some(Weight::Light)`.
    fn light(self) -> Self {
        self.weight(Weight::Light)
    }

    /// Sets `Some(Weight::ResetWeight)`.
    fn reset_weight(self) -> Self {
        self.weight(Weight::ResetWeight)
    }

    /// `None`s `Option<Weight>`.
    fn no_weight(self) -> Self {
        self.weight(None)
    }

    /// Sets `Option<Slant>`.
    fn slant(self, slant: impl Into<Option<Slant>>) -> Self;

    /// Sets `Some(Slant::Italic)`.
    fn italic(self) -> Self {
        self.slant(Slant::Italic)
    }

    /// Sets `Some(Slant::ResetSlant)`.
    fn reset_slant(self) -> Self {
        self.slant(Slant::ResetSlant)
    }

    /// `None`s `Option<Slant>`.
    fn no_slant(self) -> Self {
        self.slant(None)
    }

    /// Sets `Option<Underline>`.
    fn underline(self, underline: impl Into<Option<Underline>>) -> Self;

    /// Sets `Some(Underline::Underlined)`.
    fn underlined(self) -> Self {
        self.underline(Underline::Underlined)
    }

    /// Sets `Some(Underline::ResetUnderline)`.
    fn reset_underline(self) -> Self {
        self.underline(Underline::ResetUnderline)
    }

    /// `None`s `Option<Underline>`.
    fn no_underline(self) -> Self {
        self.underline(None)
    }

    /// Sets `Option<Strike>`.
    fn strike(self, strike: impl Into<Option<Strike>>) -> Self;

    /// Sets `Some(Strike::Striked)`.
    fn striked(self) -> Self {
        self.strike(Strike::Striked)
    }

    /// Sets `Some(Strike::ResetStrike)`.
    fn reset_strike(self) -> Self {
        self.strike(Strike::ResetStrike)
    }

    /// `None`s `Option<Strike>`.
    fn no_strike(self) -> Self {
        self.strike(None)
    }

    /// Sets `Option<Overline>`.
    fn overline(self, overline: impl Into<Option<Overline>>) -> Self;

    /// Sets `Some(Overline::Ovelined)`.
    fn ovelined(self) -> Self {
        self.overline(Overline::Ovelined)
    }

    /// Sets `Some(Overline::ResetOverline)`.
    fn reset_overline(self) -> Self {
        self.overline(Overline::ResetOverline)
    }

    /// `None`s `Option<Overline>`.
    fn no_overline(self) -> Self {
        self.overline(None)
    }

    /// Sets `Option<Invert>`.
    fn invert(self, invert: impl Into<Option<Invert>>) -> Self;

    /// Sets `Some(Invert::Inverted)`.
    fn inverted(self) -> Self {
        self.invert(Invert::Inverted)
    }

    /// Sets `Some(Invert::ResetInvert)`.
    fn reset_invert(self) -> Self {
        self.invert(Invert::ResetInvert)
    }

    /// `None`s `Option<Invert>`.
    fn no_invert(self) -> Self {
        self.invert(None)
    }

    /// Sets `Option<Blink>`.
    fn blink(self, blink: impl Into<Option<Blink>>) -> Self;

    /// Sets `Some(Blink::Slow)`.
    fn slow(self) -> Self {
        self.blink(Blink::Slow)
    }

    /// Sets `Some(Blink::Fast)`.
    fn fast(self) -> Self {
        self.blink(Blink::Fast)
    }

    /// Sets `Some(Blink::ResetBlink)`.
    fn reset_blink(self) -> Self {
        self.blink(Blink::ResetBlink)
    }

    /// `None`s `Option<Blink>`.
    fn no_blink(self) -> Self {
        self.blink(None)
    }

    /// Sets `Option<Border>`.
    fn border(self, border: impl Into<Option<Border>>) -> Self;

    /// Sets `Some(Border::Circle)`.
    fn circle(self) -> Self {
        self.border(Border::Circle)
    }

    /// Sets `Some(Border::Frame)`.
    fn frame(self) -> Self {
        self.border(Border::Frame)
    }

    /// Sets `Some(Border::ResetBorder)`.
    fn reset_border(self) -> Self {
        self.border(Border::ResetBorder)
    }

    /// `None`s `Option<Border>`.
    fn no_border(self) -> Self {
        self.border(None)
    }
}
