////////////////////////////////////////////////////////////////////////////////
// 🚨🚨🚨🚨🚨🚨🚨🚨 This file is @generated by build script. 🚨🚨🚨🚨🚨🚨🚨🚨 //
// 🚧🚧🚧🚧🚧🚧🚧🚧           ⛔ DO NOT MODIFY! ⛔           🚧🚧🚧🚧🚧🚧🚧🚧 //
////////////////////////////////////////////////////////////////////////////////

use crate::*;
use std::fmt::{Display, Error, Formatter};

/// `Style`s.
///
/// A straightforward implementation of `Styler`.
///
/// `Display`s the corresponding CSIs to the terminal.
///
/// `Default`s as an empty `Style` (all fields set to `None`).
#[derive(Copy, Clone, Eq, PartialEq, Default, Debug)]
pub struct Style {
    pub foreground: Option<Foreground>,
    pub background: Option<Background>,
    pub weight:     Option<Weight>,
    pub slant:      Option<Slant>,
    pub underline:  Option<Underline>,
    pub strike:     Option<Strike>,
    pub overline:   Option<Overline>,
    pub invert:     Option<Invert>,
    pub blink:      Option<Blink>,
    pub border:     Option<Border>,
}

impl Style {
    /// A `Style` with fields set to `None`.
    pub const NONE: Self = Self {
        foreground: None,
        background: None,
        weight:     None,
        slant:      None,
        underline:  None,
        strike:     None,
        overline:   None,
        invert:     None,
        blink:      None,
        border:     None,
    };
    /// A `Style` with fields set to their reset value.
    pub const RESET: Self = Self {
        foreground: Some(Foreground(Color::ResetColor)),
        background: Some(Background(Color::ResetColor)),
        weight:     Some(Weight::ResetWeight),
        slant:      Some(Slant::ResetSlant),
        underline:  Some(Underline::ResetUnderline),
        strike:     Some(Strike::ResetStrike),
        overline:   Some(Overline::ResetOverline),
        invert:     Some(Invert::ResetInvert),
        blink:      Some(Blink::ResetBlink),
        border:     Some(Border::ResetBorder),
    };
}

impl Display for Style {
    fn fmt(&self, f: &mut Formatter) -> Result<(), Error> {
        if let Some(foreground) = self.get_foreground() {
            <Foreground as Display>::fmt(&foreground, f)?;
        }

        if let Some(background) = self.get_background() {
            <Background as Display>::fmt(&background, f)?;
        }

        if let Some(weight) = self.get_weight() {
            <Weight as Display>::fmt(&weight, f)?;
        }

        if let Some(slant) = self.get_slant() {
            <Slant as Display>::fmt(&slant, f)?;
        }

        if let Some(underline) = self.get_underline() {
            <Underline as Display>::fmt(&underline, f)?;
        }

        if let Some(strike) = self.get_strike() {
            <Strike as Display>::fmt(&strike, f)?;
        }

        if let Some(overline) = self.get_overline() {
            <Overline as Display>::fmt(&overline, f)?;
        }

        if let Some(invert) = self.get_invert() {
            <Invert as Display>::fmt(&invert, f)?;
        }

        if let Some(blink) = self.get_blink() {
            <Blink as Display>::fmt(&blink, f)?;
        }

        if let Some(border) = self.get_border() {
            <Border as Display>::fmt(&border, f)?;
        }

        Ok(())
    }
}

// ========================================================================== //
// ========================================================================== //
//                                Conversions                                 //
// ========================================================================== //
// ========================================================================== //

/// Returns an empty `Style` with `Some(foreground)`.
impl From<Foreground> for Style {
    /// Returns an empty `Style` with `Some(foreground)`.
    fn from(foreground: Foreground) -> Self {
        Self {
            foreground: Some(foreground),
            background: None,
            weight:     None,
            slant:      None,
            underline:  None,
            strike:     None,
            overline:   None,
            invert:     None,
            blink:      None,
            border:     None,
        }
    }
}

/// Returns an empty `Style` with `Some(background)`.
impl From<Background> for Style {
    /// Returns an empty `Style` with `Some(background)`.
    fn from(background: Background) -> Self {
        Self {
            foreground: None,
            background: Some(background),
            weight:     None,
            slant:      None,
            underline:  None,
            strike:     None,
            overline:   None,
            invert:     None,
            blink:      None,
            border:     None,
        }
    }
}

/// Returns an empty `Style` with `Some(weight)`.
impl From<Weight> for Style {
    /// Returns an empty `Style` with `Some(weight)`.
    fn from(weight: Weight) -> Self {
        Self {
            foreground: None,
            background: None,
            weight:     Some(weight),
            slant:      None,
            underline:  None,
            strike:     None,
            overline:   None,
            invert:     None,
            blink:      None,
            border:     None,
        }
    }
}

/// Returns an empty `Style` with `Some(slant)`.
impl From<Slant> for Style {
    /// Returns an empty `Style` with `Some(slant)`.
    fn from(slant: Slant) -> Self {
        Self {
            foreground: None,
            background: None,
            weight:     None,
            slant:      Some(slant),
            underline:  None,
            strike:     None,
            overline:   None,
            invert:     None,
            blink:      None,
            border:     None,
        }
    }
}

/// Returns an empty `Style` with `Some(underline)`.
impl From<Underline> for Style {
    /// Returns an empty `Style` with `Some(underline)`.
    fn from(underline: Underline) -> Self {
        Self {
            foreground: None,
            background: None,
            weight:     None,
            slant:      None,
            underline:  Some(underline),
            strike:     None,
            overline:   None,
            invert:     None,
            blink:      None,
            border:     None,
        }
    }
}

/// Returns an empty `Style` with `Some(strike)`.
impl From<Strike> for Style {
    /// Returns an empty `Style` with `Some(strike)`.
    fn from(strike: Strike) -> Self {
        Self {
            foreground: None,
            background: None,
            weight:     None,
            slant:      None,
            underline:  None,
            strike:     Some(strike),
            overline:   None,
            invert:     None,
            blink:      None,
            border:     None,
        }
    }
}

/// Returns an empty `Style` with `Some(overline)`.
impl From<Overline> for Style {
    /// Returns an empty `Style` with `Some(overline)`.
    fn from(overline: Overline) -> Self {
        Self {
            foreground: None,
            background: None,
            weight:     None,
            slant:      None,
            underline:  None,
            strike:     None,
            overline:   Some(overline),
            invert:     None,
            blink:      None,
            border:     None,
        }
    }
}

/// Returns an empty `Style` with `Some(invert)`.
impl From<Invert> for Style {
    /// Returns an empty `Style` with `Some(invert)`.
    fn from(invert: Invert) -> Self {
        Self {
            foreground: None,
            background: None,
            weight:     None,
            slant:      None,
            underline:  None,
            strike:     None,
            overline:   None,
            invert:     Some(invert),
            blink:      None,
            border:     None,
        }
    }
}

/// Returns an empty `Style` with `Some(blink)`.
impl From<Blink> for Style {
    /// Returns an empty `Style` with `Some(blink)`.
    fn from(blink: Blink) -> Self {
        Self {
            foreground: None,
            background: None,
            weight:     None,
            slant:      None,
            underline:  None,
            strike:     None,
            overline:   None,
            invert:     None,
            blink:      Some(blink),
            border:     None,
        }
    }
}

/// Returns an empty `Style` with `Some(border)`.
impl From<Border> for Style {
    /// Returns an empty `Style` with `Some(border)`.
    fn from(border: Border) -> Self {
        Self {
            foreground: None,
            background: None,
            weight:     None,
            slant:      None,
            underline:  None,
            strike:     None,
            overline:   None,
            invert:     None,
            blink:      None,
            border:     Some(border),
        }
    }
}

// ========================================================================== //
// ========================================================================== //
//                               Styler* traits                               //
// ========================================================================== //
// ========================================================================== //

impl StylerIndex for Style {
    fn get_foreground(&self) -> Option<Foreground> {
        self.foreground
    }

    fn get_background(&self) -> Option<Background> {
        self.background
    }

    fn get_weight(&self) -> Option<Weight> {
        self.weight
    }

    fn get_slant(&self) -> Option<Slant> {
        self.slant
    }

    fn get_underline(&self) -> Option<Underline> {
        self.underline
    }

    fn get_strike(&self) -> Option<Strike> {
        self.strike
    }

    fn get_overline(&self) -> Option<Overline> {
        self.overline
    }

    fn get_invert(&self) -> Option<Invert> {
        self.invert
    }

    fn get_blink(&self) -> Option<Blink> {
        self.blink
    }

    fn get_border(&self) -> Option<Border> {
        self.border
    }
}

impl StylerIndexMut for Style {
    fn get_foreground_mut(&mut self) -> &mut Option<Foreground> {
        &mut self.foreground
    }

    fn get_background_mut(&mut self) -> &mut Option<Background> {
        &mut self.background
    }

    fn get_weight_mut(&mut self) -> &mut Option<Weight> {
        &mut self.weight
    }

    fn get_slant_mut(&mut self) -> &mut Option<Slant> {
        &mut self.slant
    }

    fn get_underline_mut(&mut self) -> &mut Option<Underline> {
        &mut self.underline
    }

    fn get_strike_mut(&mut self) -> &mut Option<Strike> {
        &mut self.strike
    }

    fn get_overline_mut(&mut self) -> &mut Option<Overline> {
        &mut self.overline
    }

    fn get_invert_mut(&mut self) -> &mut Option<Invert> {
        &mut self.invert
    }

    fn get_blink_mut(&mut self) -> &mut Option<Blink> {
        &mut self.blink
    }

    fn get_border_mut(&mut self) -> &mut Option<Border> {
        &mut self.border
    }
}

impl Styler for Style {
    type Output = Self;

    fn foreground(self, foreground: impl Into<Option<Foreground>>) -> Self::Output {
        Style {
            foreground: foreground.into(),
            ..self
        }
    }

    fn background(self, background: impl Into<Option<Background>>) -> Self::Output {
        Style {
            background: background.into(),
            ..self
        }
    }

    fn weight(self, weight: impl Into<Option<Weight>>) -> Self::Output {
        Style {
            weight: weight.into(),
            ..self
        }
    }

    fn slant(self, slant: impl Into<Option<Slant>>) -> Self::Output {
        Style {
            slant: slant.into(),
            ..self
        }
    }

    fn underline(self, underline: impl Into<Option<Underline>>) -> Self::Output {
        Style {
            underline: underline.into(),
            ..self
        }
    }

    fn strike(self, strike: impl Into<Option<Strike>>) -> Self::Output {
        Style {
            strike: strike.into(),
            ..self
        }
    }

    fn overline(self, overline: impl Into<Option<Overline>>) -> Self::Output {
        Style {
            overline: overline.into(),
            ..self
        }
    }

    fn invert(self, invert: impl Into<Option<Invert>>) -> Self::Output {
        Style {
            invert: invert.into(),
            ..self
        }
    }

    fn blink(self, blink: impl Into<Option<Blink>>) -> Self::Output {
        Style {
            blink: blink.into(),
            ..self
        }
    }

    fn border(self, border: impl Into<Option<Border>>) -> Self::Output {
        Style {
            border: border.into(),
            ..self
        }
    }
}

impl StylerMut for Style {
    fn foreground_mut(&mut self, foreground: impl Into<Option<Foreground>>) {
        self.foreground = foreground.into();
    }

    fn background_mut(&mut self, background: impl Into<Option<Background>>) {
        self.background = background.into();
    }

    fn weight_mut(&mut self, weight: impl Into<Option<Weight>>) {
        self.weight = weight.into();
    }

    fn slant_mut(&mut self, slant: impl Into<Option<Slant>>) {
        self.slant = slant.into();
    }

    fn underline_mut(&mut self, underline: impl Into<Option<Underline>>) {
        self.underline = underline.into();
    }

    fn strike_mut(&mut self, strike: impl Into<Option<Strike>>) {
        self.strike = strike.into();
    }

    fn overline_mut(&mut self, overline: impl Into<Option<Overline>>) {
        self.overline = overline.into();
    }

    fn invert_mut(&mut self, invert: impl Into<Option<Invert>>) {
        self.invert = invert.into();
    }

    fn blink_mut(&mut self, blink: impl Into<Option<Blink>>) {
        self.blink = blink.into();
    }

    fn border_mut(&mut self, border: impl Into<Option<Border>>) {
        self.border = border.into();
    }
}
