////////////////////////////////////////////////////////////////////////////////
// 🚨🚨🚨🚨🚨🚨🚨🚨 This file is @generated by build script. 🚨🚨🚨🚨🚨🚨🚨🚨 //
// 🚧🚧🚧🚧🚧🚧🚧🚧           ⛔ DO NOT MODIFY! ⛔           🚧🚧🚧🚧🚧🚧🚧🚧 //
////////////////////////////////////////////////////////////////////////////////

use crate::*;

/// A trait for getting `Option`al attributes on styled types.
pub trait StylerIndex {
    /// Gets `Option<Foreground>`.
    fn get_foreground(&self) -> Option<Foreground>;

    /// Gets `Option<Background>`.
    fn get_background(&self) -> Option<Background>;

    /// Gets `Option<Weight>`.
    fn get_weight(&self) -> Option<Weight>;

    /// Gets `Option<Slant>`.
    fn get_slant(&self) -> Option<Slant>;

    /// Gets `Option<Underline>`.
    fn get_underline(&self) -> Option<Underline>;

    /// Gets `Option<Strike>`.
    fn get_strike(&self) -> Option<Strike>;

    /// Gets `Option<Overline>`.
    fn get_overline(&self) -> Option<Overline>;

    /// Gets `Option<Invert>`.
    fn get_invert(&self) -> Option<Invert>;

    /// Gets `Option<Blink>`.
    fn get_blink(&self) -> Option<Blink>;

    /// Gets `Option<Border>`.
    fn get_border(&self) -> Option<Border>;

    /// Returns a `Style`.
    fn style(&self) -> Style {
        Style {
            foreground: self.get_foreground(),
            background: self.get_background(),
            weight:     self.get_weight(),
            slant:      self.get_slant(),
            underline:  self.get_underline(),
            strike:     self.get_strike(),
            overline:   self.get_overline(),
            invert:     self.get_invert(),
            blink:      self.get_blink(),
            border:     self.get_border(),
        }
    }
}

/// A trait for getting `Option`al attributes on mutable styled types.
pub trait StylerIndexMut {
    /// Gets `&mut Option<Foreground>`.
    fn get_foreground(&mut self) -> &mut Option<Foreground>;

    /// Gets `&mut Option<Background>`.
    fn get_background(&mut self) -> &mut Option<Background>;

    /// Gets `&mut Option<Weight>`.
    fn get_weight(&mut self) -> &mut Option<Weight>;

    /// Gets `&mut Option<Slant>`.
    fn get_slant(&mut self) -> &mut Option<Slant>;

    /// Gets `&mut Option<Underline>`.
    fn get_underline(&mut self) -> &mut Option<Underline>;

    /// Gets `&mut Option<Strike>`.
    fn get_strike(&mut self) -> &mut Option<Strike>;

    /// Gets `&mut Option<Overline>`.
    fn get_overline(&mut self) -> &mut Option<Overline>;

    /// Gets `&mut Option<Invert>`.
    fn get_invert(&mut self) -> &mut Option<Invert>;

    /// Gets `&mut Option<Blink>`.
    fn get_blink(&mut self) -> &mut Option<Blink>;

    /// Gets `&mut Option<Border>`.
    fn get_border(&mut self) -> &mut Option<Border>;
}

/// A trait for setting `Option`al attributes on styled types.
pub trait Styler: StylerIndex + Sized {
    /// The resulting type of the setters.
    type Output;

    /// Sets `Option<Foreground>`.
    fn foreground(self, foreground: impl Into<Option<Foreground>>) -> Self;

    /// `None`s `Option<Foreground>`.
    fn no_foreground(self) -> Self {
        self.foreground(None)
    }

    /// Sets `Option<Background>`.
    fn background(self, background: impl Into<Option<Background>>) -> Self;

    /// `None`s `Option<Background>`.
    fn no_background(self) -> Self {
        self.background(None)
    }

    /// Sets `Option<Weight>`.
    fn weight(self, weight: impl Into<Option<Weight>>) -> Self;

    /// `None`s `Option<Weight>`.
    fn no_weight(self) -> Self {
        self.weight(None)
    }

    /// Sets `Option<Slant>`.
    fn slant(self, slant: impl Into<Option<Slant>>) -> Self;

    /// `None`s `Option<Slant>`.
    fn no_slant(self) -> Self {
        self.slant(None)
    }

    /// Sets `Option<Underline>`.
    fn underline(self, underline: impl Into<Option<Underline>>) -> Self;

    /// `None`s `Option<Underline>`.
    fn no_underline(self) -> Self {
        self.underline(None)
    }

    /// Sets `Option<Strike>`.
    fn strike(self, strike: impl Into<Option<Strike>>) -> Self;

    /// `None`s `Option<Strike>`.
    fn no_strike(self) -> Self {
        self.strike(None)
    }

    /// Sets `Option<Overline>`.
    fn overline(self, overline: impl Into<Option<Overline>>) -> Self;

    /// `None`s `Option<Overline>`.
    fn no_overline(self) -> Self {
        self.overline(None)
    }

    /// Sets `Option<Invert>`.
    fn invert(self, invert: impl Into<Option<Invert>>) -> Self;

    /// `None`s `Option<Invert>`.
    fn no_invert(self) -> Self {
        self.invert(None)
    }

    /// Sets `Option<Blink>`.
    fn blink(self, blink: impl Into<Option<Blink>>) -> Self;

    /// `None`s `Option<Blink>`.
    fn no_blink(self) -> Self {
        self.blink(None)
    }

    /// Sets `Option<Border>`.
    fn border(self, border: impl Into<Option<Border>>) -> Self;

    /// `None`s `Option<Border>`.
    fn no_border(self) -> Self {
        self.border(None)
    }
}
